### ISSUE TITLE
Describe known issue: Resource not accessible by integration (repository.pullRequest)

### ISSUE THREAD

**Issue by 030** [schubergphilis/mcvs-pr-validation-action#6]
When using this action outside SBP: a permission issue occurs that should be resolved by adding the following:

```
permissions:
  contents: read
  pull-requests: read
jobs:
```
